### ISSUE TITLE
we should support windows

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#109]
because some commercial OCaml software developpers are forced to support it
and it may gain more users to the project

PS: I know, nobody likes to work under windows

**Comment by UnixJunkie** [comment]
Dumping to .sh and to a makefile is a cheap way to support windows.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-obuild/obuild/issues/130

**Comment by jeromemaloberti** [comment]
Actually, obuild works fine in cygwin, the only restriction is library-plugin which doesn't seem to work. I disabled it when os_type is not Unix, so unless it is explicitly specified, obuild support Windows.

**Comment by UnixJunkie** [comment]
This is amazing man !
