### ISSUE TITLE
ppx support as well as pp

### ISSUE THREAD

**Issue by avsm** [ocaml-obuild/obuild#12]
The new `ppx` option is an alternative approach to simplify camlp4, and is gaining traction bit by bit.  Adding an option to use it in obuild would help experiment with these new extensions. See http://lists.ocaml.org/pipermail/wg-camlp4/2013-January/000000.html for some links to interesting projects that use `ppx`.

**Comment by UnixJunkie** [comment]
Someone on caml-list woulld like to use ppx and obuild.
https://sympa.inria.fr/sympa/arc/caml-list/2016-03/msg00107.html

**Comment by jeromemaloberti** [comment]
Ok, I will work on it today ...

**Comment by UnixJunkie** [comment]
Florian, the poster from caml-list, can help with the testing of the feature. I will also do my best to help.

**Comment by jeromemaloberti** [comment]
I pushed a preliminary change, I'm not an expert at ppx, so please test.
It can use lwt ppx, but not yet bin_prot or anything that uses ppx_driver.
The syntax is:
  ppx: lwt.ppx.

Please report as many errors as possible before the design is getting too hard to change.
Also, if you have special cases, please ask.

**Comment by UnixJunkie** [comment]
I will try with the deriving syntax extansion on an example.

**Comment by UnixJunkie** [comment]
I sent a small fix pull request so that the configure step would work for me.

**Comment by UnixJunkie** [comment]
What is the simplest ppx we could try, I tried deriving but I am not sure it is supposed to work.

**Comment by UnixJunkie** [comment]
I tried this:

    Name: test
    Version: 1.0
    Authors: fbr
    License: GPL
    Synopsis: obuild ppx support test
    obuild-ver: 1

    Executable batch
      src-dir: .
      ppx: ppx_deriving.std
      main-is: test.ml

**Comment by UnixJunkie** [comment]
And got this:

error: unexpected parse error 'unknown token 'ID[ppxopt]' in meta file
( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_show.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_show.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_show.cmxa" ID[exists_if] = "ppx_deriving_show.cma" ) ID[package] "eq" ( ID[version] = "3.2" ID[description] = "[@@deriving eq]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_eq.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_eq.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_eq.cmxa" ID[exists_if] = "ppx_deriving_eq.cma" ) ID[package] "ord" ( ID[version] = "3.2" ID[description] = "[@@deriving ord]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_ord.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_ord.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_ord.cmxa" ID[exists_if] = "ppx_deriving_ord.cma" ) ID[package] "enum" ( ID[version] = "3.2" ID[description] = "[@@deriving enum]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_enum.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_enum.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_enum.cmxa" ID[exists_if] = "ppx_deriving_enum.cma" ) ID[package] "iter" ( ID[version] = "3.2" ID[description] = "[@@deriving iter]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_iter.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_iter.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_iter.cmxa" ID[exists_if] = "ppx_deriving_iter.cma" ) ID[package] "map" ( ID[version] = "3.2" ID[description] = "[@@deriving map]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_map.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_map.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_map.cmxa" ID[exists_if] = "ppx_deriving_map.cma" ) ID[package] "fold" ( ID[version] = "3.2" ID[description] = "[@@deriving fold]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_fold.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_fold.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_fold.cmxa" ID[exists_if] = "ppx_deriving_fold.cma" ) ID[package] "create" ( ID[version] = "3.2" ID[description] = "[@@deriving create]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_create.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_create.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_create.cmxa" ID[exists_if] = "ppx_deriving_create.cma" ) ID[package] "make" ( ID[version] = "3.2" ID[description] = "[@@deriving make]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_make.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_make.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_make.cmxa" ID[exists_if] = "ppx_deriving_make.cma" )' in meta file /home/berenger/.opam/4.02.3/lib/ppx_deriving/META

**Comment by jeromemaloberti** [comment]
ppx.deriving uses ppx_driver which cannot be parsed and I cannot yet understand how to generate the command line. Actually I need a simple example of ppx deriving or bin_prot with ocamlfind, so I can spy how it is generated.
If you look at the META of you ppx processor, anything with no parameters (ppxopt) and no predicate should work (for example ppx = "bla").

**Comment by jeromemaloberti** [comment]
Actually, I would be interested in examples with ppxopt.

**Comment by jeromemaloberti** [comment]
I pushed a much better version that can work with ppx_deriving. Hopefully it will also work with bin_prot. I removed the ppx keyword, you just add the ppx extension to the build-deps.

    Executable batch
      src-dir: .
      build-deps: ppx_deriving.std
      main-is: test.ml

Tests and bug reports would be appreciated. Thanks.

**Comment by UnixJunkie** [comment]
I'll try. Sorry I have been busy with other things recently.

**Comment by jeromemaloberti** [comment]
I pushed a much better version that can work with ppx_deriving. Hopefully it will also work with bin_prot. I removed the ppx keyword, you just add the ppx extension to the build-deps.

    Executable batch
      src-dir: .
      build-deps: ppx_deriving.std
      main-is: test.ml

Tests and bug reports would be appreciated. Thanks.

**Comment by jeromemaloberti** [comment]
I just pushed a working (with all the tests) version.
Reopen or create new tickets if you find a bug.

**Comment by UnixJunkie** [comment]
Thanks a lot Jerome ! :)

**Comment by UnixJunkie** [comment]
Where are the new tests ?
I could successfully run all the tests in my github.com:UnixJunkie/obuild-ppx-tests.git repository (deriving, sexplib, binprot).
I'd like that we keep them for future use.
If useful, I can put them under some specific directory inside of the current obuild tests.
