### ISSUE TITLE
In the X.obuild file, it should be allowed to have several dirs in the "Path:" section

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#124]
It might help people porting projects to build under obuild.
Currently, when you port a project from a Makefile (for example) to obuild,
you are forced to reorganize your project into sub libraries.
I think this is bad (think about a project you enter, already big
and you have no idea of the codebase organization).
If you have to move files around, this is not cool.
Switching to another build system should be just that and not involve other tasks
which might disrupt other people on the project.

**Comment by jeromemaloberti** [comment]
I just pushed a change on master for that.
Can you test it please ?

**Comment by UnixJunkie** [comment]
I tested and it works. Thanks a lot!
