### ISSUE TITLE
Compile standalone mli

### ISSUE THREAD

**Issue by rgrinberg** [ocaml-obuild/obuild#127]
Some mli files don't need an implementation. For example in cohttp https://github.com/mirage/ocaml-cohttp/blob/master/lib/s.mli

Obuild should handle this.

**Comment by UnixJunkie** [comment]
Can you create a dummy project with such a file and an obuild file so that the feature can be tested?

**Comment by UnixJunkie** [comment]
@rgrinberg

**Comment by jeromemaloberti** [comment]
Done in master.
Tests appreciated.

**Comment by UnixJunkie** [comment]
@rgrinberg can you test it since you reported the erroneous behavior? Also, you didn't provide a reproducible example.

**Comment by jeromemaloberti** [comment]
There's not really a need for a reproducible example, I tested on cohttp that use this feature, and it worked.
