### ISSUE TITLE
Failure to build with core_bench

### ISSUE THREAD

**Issue by rgrinberg** [ocaml-obuild/obuild#129]
The project that triggers this error is here: https://github.com/rgrinberg/ocaml-hamt

I tried simplifying it to get a smaller test case but unfortunately failed. The particular error (after running `obuild build`) is:

```
|| [10 of 11] Linking executable dist/build/bench1/bench1
|| 
|| File "_none_", line 1:
|| Error: No implementations provided for the following modules:
||          Thread referenced from /Users/rgrinberg/.opam/4.02.1/lib/core/core.cmxa(Core)
||          Mutex referenced from /Users/rgrinberg/.opam/4.02.1/lib/core/core.cmxa(Core)
||          Condition referenced from /Users/rgrinberg/.opam/4.02.1/lib/core/core.cmxa(Core)
||          Event referenced from /Users/rgrinberg/.opam/4.02.1/lib/core/core.cmxa(Core)

```

**Comment by UnixJunkie** [comment]
Don't you miss many deps? Core, Core_kernel, etc.?

**Comment by jeromemaloberti** [comment]
It seems to be an issue with the thread detection of obuild.
I will try to reproduce it, maybe it is an issue with the META file of core_bench.

**Comment by jeromemaloberti** [comment]
Ok, so threads.cmxa is not added as a dependency at link time, but -thread is correctly set ... i need to investigate why.

**Comment by rgrinberg** [comment]
> Don't you miss many deps? Core, Core_kernel, etc.?

Nope. Those are all specified as dependencies of core_bench in the meta. I did try adding them though. There was no effect.

Thanks @jeromemaloberti let me know  if there's anything I can do to help you fix this. Btw, it seems like this bug present in older version of obuild. I talked to someone on irc that said 0.0.9 built my project just fine.

**Comment by jeromemaloberti** [comment]
The problem came from the new algorithm to solve dependencies requirement
in META files. I implemented the ocamlfind algorithm which requires to know
which thread version (posix or vm) is necessary.
It is not difficult to fix, I will do it in the following days.

**Comment by jeromemaloberti** [comment]
Ok, I pushed a fix on master. Can you test it please ?
It worked on ocaml-hamt on my machine, but it is better to double check.

**Comment by rgrinberg** [comment]
@jeromemaloberti it works :100: 

Would be great to have a release as well so I can release my code that depends on obuild :)

**Comment by jeromemaloberti** [comment]
The new version has been released on opam.
