### ISSUE TITLE
Fatal error: exception Prepare.Module.DependencyNoOutput

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#134]
I could isolate this problem in a very small test project

**Comment by UnixJunkie** [comment]
It's in there:
https://github.com/UnixJunkie/obuild-bug-01

**Comment by UnixJunkie** [comment]
I was using obuild.0.1.3 from the official opam repository

**Comment by UnixJunkie** [comment]
Is this bug very hard to correct?

**Comment by jeromemaloberti** [comment]
I believe this bug is fixed for some time now. Please reopen if I'm wrong.

**Comment by UnixJunkie** [comment]
Yes it was corrected: there is a better error message now which gives the unbound module name.
