### ISSUE TITLE
in case the main file is not found, there is a cryptic error message

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#148]
Fatal error: exception Utils.FileNotFoundInPaths(_)
Instead of giving the file name that was not found.
Just delete the file listed in main-is: ...
in the .obuild file to reproduce.

**Comment by jeromemaloberti** [comment]
Fixed in master.

**Comment by UnixJunkie** [comment]
Excellent! Works for me too. We should make a new tag; I will update the opam package then.
Just ping me.

**Comment by UnixJunkie** [comment]
no new tag?

**Comment by jeromemaloberti** [comment]
Done. Sorry for the delay.
