### ISSUE TITLE
problem with ocamlfind 1.5.6

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#149]
https://gist.github.com/UnixJunkie/c180705332c90043cc10

**Comment by UnixJunkie** [comment]
The META file from ~/.opam/4.02.3/lib/num/META
https://gist.github.com/UnixJunkie/daa8acefb891df91c1a6

**Comment by UnixJunkie** [comment]
error: unexpected parse error 'unknown token 'ID[plugin]' in meta file
( ID[byte] ) = "nums.cma" ID[plugin] ( ID[native] ) = "nums.cmxs" )' in meta file /home/berenger/.opam/4.02.3/lib/num/META

**Comment by UnixJunkie** [comment]
pinning ocamlfind to 1.5.5 (previous version) with opam allows to workaround the problem.

**Comment by jeromemaloberti** [comment]
I understand the problem, I will fix it soon.

**Comment by UnixJunkie** [comment]
Thanks Jerome!

**Comment by jeromemaloberti** [comment]
Fix in master.

**Comment by UnixJunkie** [comment]
I confirm the fix works for me too.
