### ISSUE TITLE
shouldn't --enable-executable-debugging automatically imply --enable-executable-bytecode

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#151]
To debug an ocaml executable; i.e. run it under ocamldebug:
it needs to be a bytecode exe compiled with debugging information on.
It seems that --enable-executable-debugging should automatically turn on
--enable-executable-bytecode.

**Comment by jeromemaloberti** [comment]
Is it really mandatory ?
I would think that you can debug with gdb ...
Also, how would it work if you have some C bindings while using ocamldebug on the bytecode ?

**Comment by UnixJunkie** [comment]
Good question.
Maybe the right alternative is to have a new flag: --enable-executable-ocamldebug.
As a synonym for bytecode+debug.

**Comment by jeromemaloberti** [comment]
Or just -g, it already exists.

**Comment by UnixJunkie** [comment]
It's recent I guess, I did not know about it.
