### ISSUE TITLE
provide ppx-using example projects

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-obuild/obuild#153]

**Comment by UnixJunkie** [comment]
I will try to provide examples for those:
 bisect_ppx
 omonad
 ppx_bin_prot
 ppx_deriving
 ppx_sexp_conv
 ppx_type_conv

**Comment by UnixJunkie** [comment]
I did one for deriving. https://github.com/UnixJunkie/obuild-ppx-tests
It crashes obuild at the configure step for now.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-obuild/obuild/issues/12

**Comment by UnixJunkie** [comment]
Configuring test-1.0...
error: unexpected parse error 'unknown token 'ID[ppxopt]' in meta file
( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_show.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_show.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_show.cmxa" ID[exists_if] = "ppx_deriving_show.cma" ) ID[package] "eq" ( ID[version] = "3.3" ID[description] = "[@@deriving eq]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_eq.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_eq.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_eq.cmxa" ID[exists_if] = "ppx_deriving_eq.cma" ) ID[package] "ord" ( ID[version] = "3.3" ID[description] = "[@@deriving ord]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_ord.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_ord.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_ord.cmxa" ID[exists_if] = "ppx_deriving_ord.cma" ) ID[package] "enum" ( ID[version] = "3.3" ID[description] = "[@@deriving enum]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_enum.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_enum.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_enum.cmxa" ID[exists_if] = "ppx_deriving_enum.cma" ) ID[package] "iter" ( ID[version] = "3.3" ID[description] = "[@@deriving iter]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_iter.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_iter.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_iter.cmxa" ID[exists_if] = "ppx_deriving_iter.cma" ) ID[package] "map" ( ID[version] = "3.3" ID[description] = "[@@deriving map]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_map.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_map.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_map.cmxa" ID[exists_if] = "ppx_deriving_map.cma" ) ID[package] "fold" ( ID[version] = "3.3" ID[description] = "[@@deriving fold]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_fold.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_fold.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_fold.cmxa" ID[exists_if] = "ppx_deriving_fold.cma" ) ID[package] "create" ( ID[version] = "3.3" ID[description] = "[@@deriving create]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_create.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_create.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_create.cmxa" ID[exists_if] = "ppx_deriving_create.cma" ) ID[package] "make" ( ID[version] = "3.3" ID[description] = "[@@deriving make]" ID[requires] ( - ID[ppx_driver] ) = "ppx_deriving" ID[ppxopt] ( - ID[ppx_driver] ) = "ppx_deriving,./ppx_deriving_make.cma" ID[requires] ( ID[ppx_driver] ) = "ppx_deriving.api" ID[archive] ( ID[ppx_driver] , ID[byte] ) = "ppx_deriving_make.cma" ID[archive] ( ID[ppx_driver] , ID[native] ) = "ppx_deriving_make.cmxa" ID[exists_if] = "ppx_deriving_make.cma" )' in meta file /home/berenger/.opam/4.02.3/lib/ppx_deriving/META

**Comment by jeromemaloberti** [comment]
It works for me, you probably didn't upgrade properly, or didn't use the right obuild binary.

**Comment by UnixJunkie** [comment]
The opam file in the sources is not enough to install after a git pin. I'll fix that.

**Comment by UnixJunkie** [comment]
Maybe it's an opam problem. I see that we have a obuild.install file so it should work.
https://github.com/ocaml/opam/issues/2485

**Comment by UnixJunkie** [comment]
I don't know how to correct the test.ml I created, if you uncomment the main function
it does not compile.

**Comment by UnixJunkie** [comment]
OK, deriving.show indeed work. I will try others soon.

**Comment by UnixJunkie** [comment]
I just added an s-expression example.
obuild fails while parsing the META file then:

    error: unexpected parse error 'parsing ppxopt failed' in meta file /home/berenger/.opam/4.02.3/lib/ppx_type_conv/META

**Comment by jeromemaloberti** [comment]
The META from ppx_type_conv is quite strange, there are 2 ppxopt with mostly equivalent pre-condition.
Is is ported from a working example with ocamlfind ?

**Comment by UnixJunkie** [comment]
I can load the program in utop but I don't even know how to compile it with ocamlbuild...

**Comment by jeromemaloberti** [comment]
ocamlbuild is not necessary.
ocamlfind ocamlc -c -verbose -package ppx_type_conv test.ml
should work, and it will give me all the information about the ppx parameters.

**Comment by UnixJunkie** [comment]
ocamlfind ocamlc -c -verbose -package ppx_sexp_conv sexp.ml

    Effective set of compiler predicates: pkg_compiler-libs,pkg_compiler-libs.common,pkg_ppx_deriving.runtime,pkg_ppx_deriving,pkg_ppx_core.for_ppx_deriving,pkg_ppx_sexp_conv.expander.for_ppx_deriving,pkg_ppx_optcomp.for_ppx_deriving,pkg_ppx_driver.for_ppx_deriving,pkg_ppx_type_conv.for_ppx_deriving,pkg_unix,pkg_bigarray,pkg_sexplib,pkg_ppx_sexp_conv,autolink,byte
+ ocamlc.opt -c -verbose -I /home/berenger/.opam/4.02.3/lib/ocaml/compiler-libs -I /home/berenger/.opam/4.02.3/lib/ppx_deriving -I /home/berenger/.opam/4.02.3/lib/ppx_core -I /home/berenger/.opam/4.02.3/lib/ppx_optcomp -I /home/berenger/.opam/4.02.3/lib/ppx_driver -I /home/berenger/.opam/4.02.3/lib/ppx_type_conv -I /home/berenger/.opam/4.02.3/lib/sexplib -I /home/berenger/.opam/4.02.3/lib/ppx_sexp_conv -ppx "/home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving /home/berenger/.opam/4.02.3/lib/ppx_core/./ppx_core.cma /home/berenger/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv_expander.cma /home/berenger/.opam/4.02.3/lib/ppx_optcomp/./ppx_optcomp.cma /home/berenger/.opam/4.02.3/lib/ppx_driver/./ppx_driver.cma /home/berenger/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv.cma /home/berenger/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv_deriving.cma /home/berenger/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv.cma" sexp.ml
+ /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving /home/berenger/.opam/4.02.3/lib/ppx_core/./ppx_core.cma /home/berenger/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv_expander.cma /home/berenger/.opam/4.02.3/lib/ppx_optcomp/./ppx_optcomp.cma /home/berenger/.opam/4.02.3/lib/ppx_driver/./ppx_driver.cma /home/berenger/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv.cma /home/berenger/.opam/4.02.3/lib/ppx_type_conv/./ppx_type_conv_deriving.cma /home/berenger/.opam/4.02.3/lib/ppx_sexp_conv/./ppx_sexp_conv.cma '/tmp/camlppx67f35c' '/tmp/camlppx2df742'
