### ISSUE TITLE
"Cannot locate deriver yojson"

### ISSUE THREAD

**Issue by spencerwi** [ocaml-obuild/obuild#156]
I've put together a project using obuild, and so far it's great.

Except that when I try to use `ppx_deriving_yojson`, I get this message:

```
$ obuild clean && obuild configure && obuild build                                                                                    
Configuring mythtvguide-0.1.0...
[1 of 4] Compiling Libmythtvguide

File "src/libmythtvguide.ml", line 20, characters 14-20:
Cannot locate deriver yojson
```

My project lives [here](https://github.com/spencerwi/mythtv-guide) -- not sure what I'm doing wrong. 

When I tried `[@@ deriving show, yojson]` before, I also ran into `Cannot locate deriver show`

**Comment by UnixJunkie** [comment]
It looks like a bug.

**Comment by UnixJunkie** [comment]
Not sure if it helps but here is the verbose build output (obuild v0.1.8):

    analyzing project
    initializing standard library : package str
    initializing standard library : package unix
    initializing standard library : package graphics
    initializing standard library : package dynlink
    initializing standard library : package nums
    initializing standard library : package bigarray
    initializing standard library : package stdlib
    initializing standard library : package libocamlviz
      getting dependencies for target exe-mythtvguide
      fetching META lwt
      library lwt depends on bytes
      fetching META bytes
      fetching META cohttp
      library cohttp depends on base64
      fetching META base64
      library base64 depends on bytes
      library cohttp depends on bytes
      library cohttp depends on sexplib
      fetching META sexplib
      library sexplib depends on bigarray
      library cohttp depends on fieldslib
      fetching META fieldslib
      library cohttp depends on uri.services
      fetching META uri
      library uri.services depends on uri
      library uri depends on sexplib
      library uri depends on stringext
      fetching META stringext
      library stringext depends on bytes
      library uri depends on re.posix
      fetching META re
      library re.posix depends on re
      library re depends on bytes
      library cohttp depends on uri
      library cohttp depends on stringext
      library cohttp depends on re.emacs
      library re.emacs depends on re
      library cohttp.lwt-core depends on cohttp
      library cohttp.lwt-core depends on uri
      library cohttp.lwt-core depends on lwt
      library cohttp.lwt depends on magic-mime
      fetching META magic-mime
      library cohttp.lwt depends on conduit.lwt-unix
      fetching META conduit
      library conduit.lwt-unix depends on uri.services
      library conduit.lwt-unix depends on ipaddr.unix
      fetching META ipaddr
      library ipaddr.unix depends on ipaddr
      library ipaddr depends on sexplib
      library ipaddr depends on bytes
      library ipaddr.unix depends on unix
      library conduit.lwt-unix depends on lwt.unix
      library lwt.unix depends on bigarray
      library lwt.unix depends on unix
      library lwt.unix depends on lwt.log
      library lwt.log depends on lwt
      library lwt.unix depends on lwt
      library conduit.lwt-unix depends on conduit.lwt
      library conduit.lwt depends on lwt
      library conduit.lwt depends on conduit
      library conduit depends on stringext
      library conduit depends on uri
      library conduit depends on cstruct
      fetching META cstruct
      library cstruct depends on sexplib
      library cstruct depends on ocplib-endian.bigstring
      fetching META ocplib-endian
      library ocplib-endian.bigstring depends on bytes
      library ocplib-endian.bigstring depends on bigarray
      library cstruct depends on ocplib-endian
      library ocplib-endian depends on bytes
      library cstruct depends on bigarray
      library cstruct depends on bytes
      library conduit depends on ipaddr
      library conduit depends on sexplib
      library cohttp.lwt depends on lwt.unix
      library cohttp.lwt depends on unix
      library cohttp.lwt depends on cohttp.lwt-core
      fetching META core
      library core depends on variantslib
      fetching META variantslib
      library core depends on typerep
      fetching META typerep
      library core depends on threads
      fetching META threads
      library threads depends on threads.posix
      library threads.posix depends on unix
      library threads depends on threads.vm
      library threads.vm depends on unix
      library core depends on sexplib.unix
      library sexplib.unix depends on unix
      library sexplib.unix depends on sexplib
      library core depends on sexplib
      library core depends on ppx_inline_test.runtime-lib
      fetching META ppx_inline_test
      library ppx_inline_test.runtime-lib depends on ppx_inline_test.config
      library core depends on ppx_expect.collector
      fetching META ppx_expect
      library ppx_expect.collector depends on ppx_inline_test.runtime-lib
      library ppx_expect.collector depends on ppx_expect.config
      library ppx_expect.collector depends on ppx_expect.common
      library ppx_expect.common depends on sexplib
      library ppx_expect.collector depends on fieldslib
      library core depends on ppx_bench.runtime-lib
      fetching META ppx_bench
      library core depends on ppx_assert.runtime-lib
      fetching META ppx_assert
      library ppx_assert.runtime-lib depends on sexplib
      library core depends on fieldslib
      library core depends on core_kernel
      fetching META core_kernel
      library core_kernel depends on variantslib
      library core_kernel depends on typerep
      library core_kernel depends on sexplib
      library core_kernel depends on result
      fetching META result
      library core_kernel depends on ppx_inline_test.runtime-lib
      library core_kernel depends on ppx_expect.collector
      library core_kernel depends on ppx_bench.runtime-lib
      library core_kernel depends on ppx_assert.runtime-lib
      library core_kernel depends on num
      fetching META num
      library num depends on num.core
      library core_kernel depends on fieldslib
      library core_kernel depends on bin_prot
      fetching META bin_prot
      library bin_prot depends on bigarray
      library core depends on bin_prot
      fetching META yojson
      library yojson depends on biniou
      fetching META biniou
      library biniou depends on easy-format
      fetching META easy-format
      library yojson depends on easy-format
      fetching META ppx_deriving
      library ppx_deriving depends on ppx_deriving.runtime
      library ppx_deriving.std depends on ppx_deriving.make
      library ppx_deriving.make depends on ppx_deriving.api
      library ppx_deriving.api depends on ppx_tools
      fetching META ppx_tools
      library ppx_tools depends on compiler-libs.common
      fetching META compiler-libs
      library compiler-libs.common depends on compiler-libs
      library ppx_deriving.api depends on compiler-libs.common
      library ppx_deriving.api depends on dynlink
      library ppx_deriving.make depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.create
      library ppx_deriving.create depends on ppx_deriving.api
      library ppx_deriving.create depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.fold
      library ppx_deriving.fold depends on ppx_deriving.api
      library ppx_deriving.fold depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.map
      library ppx_deriving.map depends on ppx_deriving.api
      library ppx_deriving.map depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.iter
      library ppx_deriving.iter depends on ppx_deriving.api
      library ppx_deriving.iter depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.enum
      library ppx_deriving.enum depends on ppx_deriving.api
      library ppx_deriving.enum depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.ord
      library ppx_deriving.ord depends on ppx_deriving.api
      library ppx_deriving.ord depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.eq
      library ppx_deriving.eq depends on ppx_deriving.api
      library ppx_deriving.eq depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.show
      library ppx_deriving.show depends on ppx_deriving.api
      library ppx_deriving.show depends on ppx_deriving
      fetching META ppx_deriving_yojson
      library ppx_deriving_yojson depends on ppx_deriving.api
      library ppx_deriving_yojson depends on ppx_deriving_yojson.runtime
      library ppx_deriving_yojson.runtime depends on yojson
      library ppx_deriving_yojson depends on ppx_deriving
    preparing target exe-mythtvguide
    preparing compilation for exe-mythtvguide
    Analysing Mythtv_guide
      Mythtv_guide has mtime 1459931063.626578
      Mythtv_guide depends on Core,Libmythtvguide,Lwt_main
      Mythtv_guide internally depends on Libmythtvguide
    Analysing Libmythtvguide
      Libmythtvguide has mtime 1459931063.626578
      Libmythtvguide depends on Client,Cohttp,Cohttp_lwt,Cohttp_lwt_body,Cohttp_lwt_unix,Core,Lwt,Uri,Yojson
      Libmythtvguide internally depends on
    [1 of 4] Compiling Libmythtvguide

    File "src/libmythtvguide.ml", line 20, characters 14-20:
    Cannot locate deriver yojson

**Comment by jeromemaloberti** [comment]
Strange, ppx_deriving_yojson is not detected as a dependency of libmythtvguide.

**Comment by jeromemaloberti** [comment]
Can you put the output of:
obuild --debug+ build 
please ?

**Comment by UnixJunkie** [comment]
Here you are:

      [CMD]: ocamlfind printconf conf
      [CMD]: /home/berenger/.opam/4.02.3/bin/ocamlopt.opt -config
    analyzing project
    initializing standard library : package str
    initializing standard library : package unix
    initializing standard library : package graphics
    initializing standard library : package dynlink
    initializing standard library : package nums
    initializing standard library : package bigarray
    initializing standard library : package stdlib
    initializing standard library : package libocamlviz
      getting dependencies for target exe-mythtvguide
      fetching META lwt
      library lwt depends on bytes
      fetching META bytes
      fetching META cohttp
      library cohttp depends on base64
      fetching META base64
      library base64 depends on bytes
      library cohttp depends on bytes
      library cohttp depends on sexplib
      fetching META sexplib
      library sexplib depends on bigarray
      library cohttp depends on fieldslib
      fetching META fieldslib
      library cohttp depends on uri.services
      fetching META uri
      library uri.services depends on uri
      library uri depends on sexplib
      library uri depends on stringext
      fetching META stringext
      library stringext depends on bytes
      library uri depends on re.posix
      fetching META re
      library re.posix depends on re
      library re depends on bytes
      library cohttp depends on uri
      library cohttp depends on stringext
      library cohttp depends on re.emacs
      library re.emacs depends on re
      library cohttp.lwt-core depends on cohttp
      library cohttp.lwt-core depends on uri
      library cohttp.lwt-core depends on lwt
      library cohttp.lwt depends on magic-mime
      fetching META magic-mime
      library cohttp.lwt depends on conduit.lwt-unix
      fetching META conduit
      library conduit.lwt-unix depends on uri.services
      library conduit.lwt-unix depends on ipaddr.unix
      fetching META ipaddr
      library ipaddr.unix depends on ipaddr
      library ipaddr depends on sexplib
      library ipaddr depends on bytes
      library ipaddr.unix depends on unix
      library conduit.lwt-unix depends on lwt.unix
      library lwt.unix depends on bigarray
      library lwt.unix depends on unix
      library lwt.unix depends on lwt.log
      library lwt.log depends on lwt
      library lwt.unix depends on lwt
      library conduit.lwt-unix depends on conduit.lwt
      library conduit.lwt depends on lwt
      library conduit.lwt depends on conduit
      library conduit depends on stringext
      library conduit depends on uri
      library conduit depends on cstruct
      fetching META cstruct
      library cstruct depends on sexplib
      library cstruct depends on ocplib-endian.bigstring
      fetching META ocplib-endian
      library ocplib-endian.bigstring depends on bytes
      library ocplib-endian.bigstring depends on bigarray
      library cstruct depends on ocplib-endian
      library ocplib-endian depends on bytes
      library cstruct depends on bigarray
      library cstruct depends on bytes
      library conduit depends on ipaddr
      library conduit depends on sexplib
      library cohttp.lwt depends on lwt.unix
      library cohttp.lwt depends on unix
      library cohttp.lwt depends on cohttp.lwt-core
      fetching META core
      library core depends on variantslib
      fetching META variantslib
      library core depends on typerep
      fetching META typerep
      library core depends on threads
      fetching META threads
      library threads depends on threads.posix
      library threads.posix depends on unix
      library threads depends on threads.vm
      library threads.vm depends on unix
      library core depends on sexplib.unix
      library sexplib.unix depends on unix
      library sexplib.unix depends on sexplib
      library core depends on sexplib
      library core depends on ppx_inline_test.runtime-lib
      fetching META ppx_inline_test
      library ppx_inline_test.runtime-lib depends on ppx_inline_test.config
      library core depends on ppx_expect.collector
      fetching META ppx_expect
      library ppx_expect.collector depends on ppx_inline_test.runtime-lib
      library ppx_expect.collector depends on ppx_expect.config
      library ppx_expect.collector depends on ppx_expect.common
      library ppx_expect.common depends on sexplib
      library ppx_expect.collector depends on fieldslib
      library core depends on ppx_bench.runtime-lib
      fetching META ppx_bench
      library core depends on ppx_assert.runtime-lib
      fetching META ppx_assert
      library ppx_assert.runtime-lib depends on sexplib
      library core depends on fieldslib
      library core depends on core_kernel
      fetching META core_kernel
      library core_kernel depends on variantslib
      library core_kernel depends on typerep
      library core_kernel depends on sexplib
      library core_kernel depends on result
      fetching META result
      library core_kernel depends on ppx_inline_test.runtime-lib
      library core_kernel depends on ppx_expect.collector
      library core_kernel depends on ppx_bench.runtime-lib
      library core_kernel depends on ppx_assert.runtime-lib
      library core_kernel depends on num
      fetching META num
      library num depends on num.core
      library core_kernel depends on fieldslib
      library core_kernel depends on bin_prot
      fetching META bin_prot
      library bin_prot depends on bigarray
      library core depends on bin_prot
      fetching META yojson
      library yojson depends on biniou
      fetching META biniou
      library biniou depends on easy-format
      fetching META easy-format
      library yojson depends on easy-format
      fetching META ppx_deriving
      library ppx_deriving depends on ppx_deriving.runtime
      library ppx_deriving.std depends on ppx_deriving.make
      library ppx_deriving.make depends on ppx_deriving.api
      library ppx_deriving.api depends on ppx_tools
      fetching META ppx_tools
      library ppx_tools depends on compiler-libs.common
      fetching META compiler-libs
      library compiler-libs.common depends on compiler-libs
      library ppx_deriving.api depends on compiler-libs.common
      library ppx_deriving.api depends on dynlink
      library ppx_deriving.make depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.create
      library ppx_deriving.create depends on ppx_deriving.api
      library ppx_deriving.create depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.fold
      library ppx_deriving.fold depends on ppx_deriving.api
      library ppx_deriving.fold depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.map
      library ppx_deriving.map depends on ppx_deriving.api
      library ppx_deriving.map depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.iter
      library ppx_deriving.iter depends on ppx_deriving.api
      library ppx_deriving.iter depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.enum
      library ppx_deriving.enum depends on ppx_deriving.api
      library ppx_deriving.enum depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.ord
      library ppx_deriving.ord depends on ppx_deriving.api
      library ppx_deriving.ord depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.eq
      library ppx_deriving.eq depends on ppx_deriving.api
      library ppx_deriving.eq depends on ppx_deriving
      library ppx_deriving.std depends on ppx_deriving.show
      library ppx_deriving.show depends on ppx_deriving.api
      library ppx_deriving.show depends on ppx_deriving
      fetching META ppx_deriving_yojson
      library ppx_deriving_yojson depends on ppx_deriving.api
      library ppx_deriving_yojson depends on ppx_deriving_yojson.runtime
      library ppx_deriving_yojson.runtime depends on yojson
      library ppx_deriving_yojson depends on ppx_deriving
    preparing target exe-mythtvguide
    preparing compilation for exe-mythtvguide
    Analysing Mythtv_guide
      Mythtv_guide has mtime 1459931063.626578
      [CMD]: /home/berenger/.opam/4.02.3/bin/ocamldep.opt -I src -I dist/build/autogen -modules src/mythtv_guide.ml src/mythtv_guide.mli
      Mythtv_guide depends on Core,Libmythtvguide,Lwt_main
      Mythtv_guide internally depends on Libmythtvguide
    Analysing Libmythtvguide
      Libmythtvguide has mtime 1459931063.626578
      [CMD]: /home/berenger/.opam/4.02.3/bin/ocamldep.opt -I src -I dist/build/autogen -modules src/libmythtvguide.ml src/libmythtvguide.mli
      Libmythtvguide depends on Client,Cohttp,Cohttp_lwt,Cohttp_lwt_body,Cohttp_lwt_unix,Core,Lwt,Uri,Yojson
      Libmythtvguide internally depends on
    [1 of 4] Compiling Libmythtvguide
      [CMD]: /home/berenger/.opam/4.02.3/bin/ocamlopt.opt -I dist/build/mythtvguide -I dist/build/autogen -I src -I /home/berenger/.opam/4.02.3/lib/ppx_deriving -I /home/berenger/.opam/4.02.3/lib/easy-format -I /home/berenger/.opam/4.02.3/lib/biniou -I /home/berenger/.opam/4.02.3/lib/yojson -I /home/berenger/.opam/4.02.3/lib/ppx_deriving_yojson -I /home/berenger/.opam/4.02.3/lib/ocaml -I /home/berenger/.opam/4.02.3/lib/ocaml/compiler-libs -I /home/berenger/.opam/4.02.3/lib/ppx_tools -I /home/berenger/.opam/4.02.3/lib/bin_prot -I /home/berenger/.opam/4.02.3/lib/fieldslib -I /home/berenger/.opam/4.02.3/lib/num -I /home/berenger/.opam/4.02.3/lib/sexplib -I /home/berenger/.opam/4.02.3/lib/ppx_assert -I /home/berenger/.opam/4.02.3/lib/ppx_bench -I /home/berenger/.opam/4.02.3/lib/ppx_expect -I /home/berenger/.opam/4.02.3/lib/ppx_inline_test -I /home/berenger/.opam/4.02.3/lib/result -I /home/berenger/.opam/4.02.3/lib/typerep -I /home/berenger/.opam/4.02.3/lib/variantslib -I /home/berenger/.opam/4.02.3/lib/core_kernel -I /home/berenger/.opam/4.02.3/lib -I /home/berenger/.opam/4.02.3/lib/core -I /home/berenger/.opam/4.02.3/lib/bytes -I /home/berenger/.opam/4.02.3/lib/lwt -I /home/berenger/.opam/4.02.3/lib/re -I /home/berenger/.opam/4.02.3/lib/stringext -I /home/berenger/.opam/4.02.3/lib/uri -I /home/berenger/.opam/4.02.3/lib/base64 -I /home/berenger/.opam/4.02.3/lib/cohttp -I /home/berenger/.opam/4.02.3/lib/ipaddr -I /home/berenger/.opam/4.02.3/lib/ocplib-endian -I /home/berenger/.opam/4.02.3/lib/cstruct -I /home/berenger/.opam/4.02.3/lib/conduit -I /home/berenger/.opam/4.02.3/lib/magic-mime -bin-annot -ppx /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving -ppx "/home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_make.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_create.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_fold.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_map.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_iter.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_enum.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_ord.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_eq.cma /home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving_show.cma" -ppx "/home/berenger/.opam/4.02.3/lib/ppx_deriving/./ppx_deriving /home/berenger/.opam/4.02.3/lib/ppx_deriving_yojson/./ppx_deriving_yojson.cma" -o dist/build/mythtvguide/libmythtvguide.cmx -c src/libmythtvguide.ml

    File "src/libmythtvguide.ml", line 20, characters 14-20:
    Cannot locate deriver yojson

**Comment by jeromemaloberti** [comment]
Ok, so you need to remove ppx_deriving and ppx_deriving.std from the build-deps.
They conflict with ppx_deriving_yojson.
ppx_deriving is a dependency to other ppx, so it is not supposed to be used by itself,
ppx_deriving.std is quite strange, it needs to be placed *after* ppx_deriving_yojson to work, maybe because it depends on it, but both can be applied.
In your current code, you don't need ppx_deriving.std, but maybe you have plan to use it ?

**Comment by spencerwi** [comment]
Wow, I'm kinda blown away. You guys not only looked into the issue I had immediately, but even checked out my code and dug into it there. Thanks so much!

You're right -- removing both `ppx_deriving` and `ppx_deriving.std` from my obuild file fixes the problem, as does sticking `ppx_deriving.std` after `ppx_deriving_yojson`. Oddly enough, if I have `ppx_deriving_yojson` before `ppx_deriving.std`, I can `[@@deriving yojson]`, but I can't `[@@deriving show, yojson]` -- I then get `Cannot locate deriver show`. In any case, I don't necessarily need any of the `std` derivers at the moment, so my problem is solved. Thank you again!

**Comment by jeromemaloberti** [comment]
I don't know much about the rules when combining ppx, I made a very small experiment with lwt.ppx and ppx_sexp, and it seems to work (I didn't test very hard though, maybe there was a problem in the code). 
If you really need both, I suggest that you split the code in different sources and uses different build-deps.

**Comment by UnixJunkie** [comment]
One problem is that this kind of "bug" report might appear again in the future.
Maybe I am asking something crazy: would it be possible to have obuild correctly re-order the build-deps if needed (and issue a warning to the user with the correct order)?
Or at least to have a message pointing the user to the fact that his build-deps
are not in the correct order.

**Comment by jeromemaloberti** [comment]
Ocamlfind is not confused, so there should be enough information to order the dependencies correctly.
I will make a test to reproduce this problem and check how ocamlfind is finding its way.
Thank you for the report.
