### ISSUE TITLE
Is this project still alive? 

### ISSUE THREAD

**Issue by xfbs** [ocaml-obuild/obuild#172]
Hey guys, is this project still alive? There doesn't seem to have been much activity recently.

**Comment by UnixJunkie** [comment]
Some people are still using it and several opam packages still rely on it.

**Comment by jpdeplaix** [comment]
I think he meant more on the development side

**Comment by jeromemaloberti** [comment]
@xfbs, sorry I don't understand your question. Obuild is working with all versions of ocaml, including 4.06. Are there features you're missing ? 
I don't have much time to work on it these days, but that doesn't mean it is dead. Obuild is not perfect and is missing some features, but it is very useful for small (and not so small) projects. And its small size makes it easy to add features when I need them.
