### ISSUE TITLE
Document obuild files

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-obuild/obuild#43]
A document that specifies precisely all the available fields in obuild files, their semantics, type and effect on build artefacts is needed. It should serve both a reference documentation for the end-user and a field name consistency checker for `obuild` developers. 

I'd suggest the following structure 

1) Describe package (top-level) fields. 
2) For each target type describe its fields and the kind of build artefacts it generates according to these fields.

**Comment by UnixJunkie** [comment]
We should complete the documentation ...
I start to hear users complaining about the lack of documentation.
It would also help with the adoption of obuild.
